2019-11-19T19:38:04|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 51, in connect
    self.add_operation("apply saved pressure", self.apply_saved_pressure)
AttributeError: 'MFCSHardware' object has no attribute 'apply_saved_pressure'

2019-11-19T19:38:06|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 51, in connect
    self.add_operation("apply saved pressure", self.apply_saved_pressure)
AttributeError: 'MFCSHardware' object has no attribute 'apply_saved_pressure'

2019-11-19T19:38:07|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 51, in connect
    self.add_operation("apply saved pressure", self.apply_saved_pressure)
AttributeError: 'MFCSHardware' object has no attribute 'apply_saved_pressure'

2019-11-19T19:38:10|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 51, in connect
    self.add_operation("apply saved pressure", self.apply_saved_pressure)
AttributeError: 'MFCSHardware' object has no attribute 'apply_saved_pressure'

2019-11-19T19:38:33|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 208, in enable_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\hardware.py", line 204, in enable_connection
    self.connect()
  File "C:\Users\Admin\Desktop\MFCS_python_old\PumpHardware.py", line 51, in connect
    self.add_operation("apply saved pressure", self.apply_saved_pressure)
AttributeError: 'MFCSHardware' object has no attribute 'apply_saved_pressure'

