2019-11-11T12:51:24|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\logged_quantity.py", line 452, in on_edit_finished
    self.update_value(widget.text())
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\logged_quantity.py", line 241, in update_value
    self.hardware_set_func(self.val)
TypeError: set_pressure_channel() takes 1 positional argument but 2 were given

