2019-02-13T09:53:31|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "C:\LabPrograms\Python\Hamamatsu_ScopeFoundry\CameraApp.py", line 180, in <module>
    app = HamamatsuApp(sys.argv)
  File "C:\LabPrograms\Python\Hamamatsu_ScopeFoundry\CameraApp.py", line 24, in __init__
    super().__init__(*kwds) # *kwds is needed since in the main we pass as argument sys.argv. Without
  File "C:\ProgramData\Anaconda3\lib\site-packages\ScopeFoundry\base_app.py", line 332, in __init__
    self.setup()
  File "C:\LabPrograms\Python\Hamamatsu_ScopeFoundry\CameraApp.py", line 140, in setup
    self.add_hardware(DmdHardware(self))
NameError: name 'DmdHardware' is not defined

